### PR TITLE
Add inverse chebyshev transform plan for Dual

### PR DESCRIPTION
**Pull request by LucasAschenbach**
I have added a method for the inverse Chebyshev transform plan on dual vectors to support transforming functionals with dual number coefficients to the value space.

This issue came up when trying to multiply two functionals with enough non-zero dual coefficients to convert to the value space.

### CODE REVIEW

**Comment by jishnub** [comment]
Could you add a test?

**Comment by LucasAschenbach** [comment]
Sure!

**Comment by LucasAschenbach** [comment]
I have added a test for the inverse Chebyshev transform on dual numbers. Should I keep the comment or remove it?

**Comment by jishnub** [comment]
I think the comment is helpful

**Comment by LucasAschenbach** [comment]
Do you mean setting the package version to `0.13.23`?

**Comment by jishnub** [comment]
Yes, exactly. I'll tag a release after merging

**Comment by LucasAschenbach** [comment]
Done 👍

**Comment by jishnub** [comment]
Thanks for the PR!

**Pull request merged**
