### PR TITLE
Fix #617

### LINKED ISSUE #617: JacobiWeight(::Int, ::Int, Jacobi(::Float64, ::Float64)) not accessing right overrides

### PR DESCRIPTION
**Pull request by ikirill**
I'm assuming `prectype` means what I think it means.

### CODE REVIEW

**Comment by dlfivefifty** [comment]
I think so: it gives the appropriate type for coefficients.

**Comment by dlfivefifty** [comment]
The tests are failing

**Comment by ikirill** [comment]
It's trickier than I thought, I'll look at this again later.

**Comment by dlfivefifty** [comment]
Closing due to inactivity.

**Pull request closed without merging**
