### PR TITLE
Closes #477

### LINKED ISSUE #477: Derivative(Laurent(PeriodicInterval())) is not diagonal.

### PR DESCRIPTION
**Pull request by MikaelSlevinsky**
This is hard to check and is failing the tests, but the derivative on the space of Laurent polynomials should be diagonal.

### CODE REVIEW

**Comment by dlfivefifty** [comment]
This fix isn't right: if j==k and bandinds == 0 the original version correctly says that the bandind == 0

The issue is that ZeroOperator has bandinds == (0,0) when they should be something like (1,-1)

**Comment by MikaelSlevinsky** [comment]
What does it mean to have band indices (1,-1)? that it's empty as viewed by an iterator?

**Comment by dlfivefifty** [comment]
Yes.  Maybe (1,0) works better with BandedMatrices.jl

**Comment by dlfivefifty** [comment]
We can also just do a check `iszerooperator` or implement the version of `InterlaceOperator` that uses a `Diagonal` matrix (that is, template out the storage)

Or make `Laurent` its own space instead of a `SumSpace`.  This is also beneficial as the "correct" blocklengths would be `1,2,2,...`, though that's likely to run into other bugs

**Pull request closed without merging**
