### PR TITLE
Remove tuplespace

### PR DESCRIPTION
**Pull request by dlfivefifty**
This unifies `ArraySpace` and `TupleSpace`, using the name `ArraySpace`.  There are two drawbacks: 
1. `ArraySpace` now stores an `Array` of (possibly different) spaces, so slightly more memory.  
2. `ArraySpace` does not template out the spaces, unlike `TupleSpace`.  I think this isn't much of an issue, as `getindex(::Tuple,k)` is not type stable anyways.

@MikaelSlevinsky any reason not to merge this?

### CODE REVIEW

**Comment by daanhb** [comment]
This choice between array and tuple looks familiar. Would it be possible/desirable to unify both? Say you make the type of the 'spaces' field itself a parameter, with the contract that it has to be an iterable and indexable list of spaces. Then it can be an array or a tuple. It is best to use an array if you have many spaces (dispatch on element types of tuples is limited anyway for long tuples) or if the types of all elements are the same. A tuple would be better for short lists and/or mixed types.

I've used that pattern a number of times, but I think it does make it more difficult for the compiler to optimize some things. For example, you have the following function
```
space(A::ArraySpace,k::Integer) = A.spaces[k]
```
which seems innocent. However, using a function like that sometimes allocates memory in my code, unexpectedly. Say you have another function:
```
function dosomethingwitharrayspace(A::ArraySpace)
  do some computation and use space(A, k)
end
```
I don't know exactly when, but quite often that turns out to allocate memory, whereas the following alternative doesn't:
```
dosomethingwitharrayspace(A::ArraySpace) = _dosomething(A, spaces(A))

function _dosomething(A::ArraySpace, spaces)
  do the exact same thing as above but with spaces[k] rather than spaces(A,k)
end
```
Anyway, I digress :-)

**Comment by daanhb** [comment]
I see now the code actually does this in other cases, like PiecewiseSpace, where the type of the spaces field is a parameter. Never mind me, carry on :-)

**Comment by dlfivefifty** [comment]
> Would it be possible/desirable to unify both? Say you make the type of the 'spaces' field itself a parameter, with the contract that it has to be an iterable and indexable list of spaces

Yes this is desirable, and I think is the plan for down the line.  The previous `ArraySpace` would then be replicated using a new type 
```julia
type Fill{T,d} <: AbstractArray{T,d}
   value::T
   dims::NTuple{d,Int}
end
```
Also, one could use `Diagonal` matrices.  
 
This is probably more important for `InterlaceOperator`.  There used to be `DiagonalInterlaceOperator` but that was removed to eventually encode `ops` as a `Diagonal` matrix.

But all of these are optimizations that are not critical at the moment (to me).  It could be easily added now, but there are many things to think through before it works well, e.g., converting between spaces with different array types.

**Comment by dlfivefifty** [comment]
I forgot that `PiecewiseSpace` already does this.  It was to solve the same problem: sometimes you want to know the types and have few of them, sometimes you don't want to know the types and have many of them

**Comment by daanhb** [comment]
It is convenient that map preserves the distinction between tuples and arrays.

Since you mention converting between spaces with different array types: any chance that you mean at some point the coefficients of a Fun won't be required to be a Vector{T} anymore? Being a vector makes linear algebra easier, but for composite spaces other data structures can be more convenient to implement.

**Comment by daanhb** [comment]
(This is not a feature request. I am just thinking about ways in which a FrameFun could be translated to a Fun in ApproxFun).

**Comment by dlfivefifty** [comment]
Yes that's also in the agenda.  I'd like to have a "GPUFun" ie a `Fun` whose coefficients are `AFArray`.  Though it would be good to have a killer use...probably more important is a "GPUBandedMwtrix" for constructibg operators.

**Comment by daanhb** [comment]
Cool! For me, killer use is ease of implementation of complicated combinations of function sets - a tuple of bases (or spaces) simply corresponds to a tuple of coefficient vectors, and so on. That must be a change with large impact on the code though, good luck ;-)

**Comment by dlfivefifty** [comment]
Well for simple bases it's already there in disguise: the coefficients are interlaced, which if interpreted as a Matrix becomes a d x Inf matrix, where d is the number of pieces

**Comment by MikaelSlevinsky** [comment]
The balance here is the rapid growth in the type parameters, say, a `Multiplication` operator, which has a `Fun` (and its own `Space`!), whose space is a `TupleSpace`, whose domains are `UnionDomain`s, arguably propagating too much information forward, vs. allocation due to type-instability (`getindex(::Tuple,k)` is only type-stable when it's in fact an `NTuple`).

In certain instances, a meta-programming solution is warranted. An example is the [HierarchicalMatrices.jl](https://github.com/MikaelSlevinsky/HierarchicalMatrices.jl) repo I'm experimenting with, where `getindex` *may be made type-stable* at the expense of pre-determining the concrete fields of a hierarchical (read block) matrix at parse time. But this get really tricky really quickly, and in the context of `ApproxFun`'s numerous domains and spaces, would be very complicated to implement. It's also complicated by the fact that other packages (at least [SingularIntegralEquations.jl](https://github.com/JuliaApproximation/SingularIntegralEquations.jl), [MultivariateOrthogonalPolynomials.jl](https://github.com/JuliaApproximation/MultivariateOrthogonalPolynomials.jl), [OscillatoryIntegrals.jl](https://github.com/JuliaApproximation/OscillatoryIntegrals.jl), and [Holomorphic.jl](https://github.com/JuliaApproximation/Holomorphic.jl)) add domains and spaces, so new parse time constructors would have to be re-exported which would be in-efficient.

@daanhb, I've bugged @dlfivefifty about the `coefficients::Vector{T}` restriction before! For instance, a `LowRankFun` could just be a `Fun{LowRankMatrix,TensorSpace}`. But there's no point rushing a beautiful thing ;).

**Comment by dlfivefifty** [comment]
Yes I think ApproxFun overuses templating.  Wrapper operators probably only need to template the `eltype` of the operators they wrap.  In fact, `PlusOperator` and `TimesOperator` use `Vector{Operator{T}}` already

**Comment by dlfivefifty** [comment]
I'm updating SingularIntegralEquations.jl, and there doesn't appear to be any issues, so I'm merging this.

**Pull request merged**
