### PR TITLE
Fix function would sometimes evaluate to 0 at left endpoint of its domain (breaking findmin)

### PR DESCRIPTION
**Pull request by ikirill**
It seems sometimes the left endpoint of a segment is being detected as being outside the domain, and the function returns 0 there. This messes up findmin/findmax, which evaluate the function at extremal_args, which include left and right endpoints.

I want to note that this change would break tests that rely on exact floating-point comparison of function values (there was at least one test there that failed so far).

The numbers `a=283....`, `b=335....` here satisfy `((a+b)-2a)/(a-b) < -1`. The mathematically equivalent form I used gives `((a-a)+(b-a))/(a-b) == -1`.

```
julia> Pkg.status("ApproxFun")
 - ApproxFun                     0.7.0+             master

julia> w = Fun(x -> 1e5/(x*x+1), 283.72074879785936 .. 335.0101119042838)
Fun(Chebyshev(【283.72074879785936,335.0101119042838】),[1.05571, -0.175023, 0.0108937, -0.00060287, 3.12819e-5, -1.55832e-6, 7.54744e-8, -3.58092e-9, 1.67245e-10, -7.71471e-12, 3.52299e-13, -1.60263e-14])

julia> w(domain(w).a)
0.0

julia> findmax(w)
(0.8910053229138628, 335.0101119042838)

julia> findmin(w)
(0.0, 283.72074879785936)
```

```
julia> Pkg.status("ApproxFun")
 - ApproxFun                     0.7.0+             pr-fix-segment-tocanonical

julia> w = Fun(x -> 1e5/(x*x+1), 283.72074879785936 .. 335.0101119042838)
Fun(Chebyshev(【283.72074879785936,335.0101119042838】),[1.05571, -0.175023, 0.0108937, -0.00060287, 3.12819e-5, -1.55832e-6, 7.54744e-8, -3.58092e-9, 1.67245e-10, -7.71471e-12, 3.52299e-13, -1.60263e-14])

julia> w(domain(w).a)
1.2422597389131171

julia> findmax(w)
(1.2422597389131171, 283.72074879785936)

julia> findmin(w)
(0.8910053229138626, 335.0101119042838)
```

### CODE REVIEW

**Comment by ikirill** [comment]
The test that failed there in CI (https://github.com/JuliaApproximation/ApproxFun.jl/blob/f016b3ffe880110c65163a8f5cecb4acb2fa8a66/test/broadcastingtest.jl#L61)
```
Test Failed
  Expression: norm.(f, [1, 2]) == norm.(F, [1, 2]) == [norm(f[1], 1), norm(f[2], 2)]
   Evaluated: [2.3504, 0.738479] == [2.3504, 0.738479] == [2.3504, 0.738479]
```
does not fail for me on my own machine. I don't get it.

**Comment by ikirill** [comment]
But I get this error on my machine now:
```
Singularities tests
    Jacobi singularity tests
ERROR: LoadError: LoadError: StackOverflowError:
Stacktrace:
 [1] _methods_by_ftype(::Any, ::Int64, ::UInt64, ::Array{UInt64,1}, ::Array{UInt64,1}) at ./reflection.jl:521
 [2] _methods_by_ftype(::ANY, ::Int64, ::UInt64) at /opt/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [3] _methods(::ANY, ::ANY, ::Int64, ::UInt64) at /opt/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [4] return_type(::ANY, ::ANY) at /opt/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [5] broadcast_c at ./broadcast.jl:310 [inlined]
 [6] broadcast(::Function, ::ApproxFun.Segment{Float64}, ::Array{Float64,1}) at ./broadcast.jl:434
 [7] points(::ApproxFun.Segment{Float64}, ::Int64) at /Users/kirill/.julia/v0.6/ApproxFun/src/Fun/Domain.jl:99
 [8] defaultFun(::ApproxFun.F, ::ApproxFun.Chebyshev{ApproxFun.Segment{Float64},Float64}, ::Int64, ::Type{Val{false}}) at /Users/kirill/.julia/v0.6/ApproxFun/src/Fun/constructors.jl:54
 [9] zerocfsFun(::ApproxFun.F, ::ApproxFun.Chebyshev{ApproxFun.Segment{Float64},Float64}) at /Users/kirill/.julia/v0.6/ApproxFun/src/Fun/constructors.jl:155
 [10] #Fun#90(::String, ::Type{T} where T, ::ApproxFun.F, ::ApproxFun.Chebyshev{ApproxFun.Segment{Float64},Float64}) at /Users/kirill/.julia/v0.6/ApproxFun/src/Fun/constructors.jl:217
 [11] #Fun#94(::Array{Any,1}, ::Type{T} where T, ::ApproxFun.F, ::ApproxFun.Segment{Float64}) at /Users/kirill/.julia/v0.6/ApproxFun/src/Fun/constructors.jl:225
 [12] #Fun#95(::Array{Any,1}, ::Type{T} where T, ::Function, ::ApproxFun.Segment{Float64}) at /Users/kirill/.julia/v0.6/ApproxFun/src/Fun/constructors.jl:226
 [13] ApproxFun.Fun(::Function, ::ApproxFun.Segment{Float64}) at /Users/kirill/.julia/v0.6/ApproxFun/src/Fun/constructors.jl:226
 [14] /(::Int64, ::ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64},Float64},Float64,Array{Float64,1}}) at /Users/kirill/.julia/v0.6/ApproxFun/src/Extras/specialfunctions.jl:156 (repeats 9294 times)
 [15] /(::Int64, ::ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64},Float64},Float64,Array{Float64,1}}) at /Users/kirill/.julia/v0.6/ApproxFun/src/Extras/specialfunctions.jl:134
 [16] /(::Int64, ::ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64},Float64},Float64,SubArray{Float64,1,Array{Float64,1},Tuple{StepRange{Int64,Int64}},true}}) at /Users/kirill/.julia/v0.6/ApproxFun/src/Extras/specialfunctions.jl:128
 [17] collect_to!(::Array{ApproxFun.Fun{ApproxFun.JacobiWeight{ApproxFun.Chebyshev{ApproxFun.Segment{Float64},Float64},ApproxFun.Segment{Float64},Float64},Float64,Array{Float64,1}},1}, ::Base.Generator{Array{ApproxFun.Fun,1},ApproxFun.##696#697{Int64}}, ::Int64, ::Int64) at ./array.jl:474
 [18] _collect(::Array{ApproxFun.Fun,1}, ::Base.Generator{Array{ApproxFun.Fun,1},ApproxFun.##696#697{Int64}}, ::Base.EltypeUnknown, ::Base.HasShape) at ./array.jl:455
 [19] /(::Int64, ::ApproxFun.Fun{ApproxFun.PiecewiseSpace{NTuple{7,ApproxFun.Chebyshev{ApproxFun.Segment{Float64},Float64}},ApproxFun.UnionDomain{NTuple{7,ApproxFun.Segment{Float64}},Float64},Float64},Float64,Array{Float64,1}}) at /Users/kirill/.julia/v0.6/ApproxFun/src/Extras/specialfunctions.jl:628
 [20] /(::Int64, ::ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64},Float64},Float64,Array{Float64,1}}) at /Users/kirill/.julia/v0.6/ApproxFun/src/Extras/specialfunctions.jl:156
 [21] include_from_node1(::String) at ./loading.jl:569
 [22] include(::String) at /opt/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [23] include_from_node1(::String) at /opt/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [24] include(::String) at /opt/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [25] process_options(::Base.JLOptions) at /opt/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [26] _start() at /opt/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/kirill/.julia/v0.6/ApproxFun/test/SingularitiesTest.jl, in expression starting on line 78
while loading /Users/kirill/.julia/v0.6/ApproxFun/test/runtests.jl, in expression starting on line 237
============================================================================================[ ERROR: ApproxFun ]============================================================================================

failed process: Process(`/opt/Julia-0.6.app/Contents/Resources/julia/bin/julia -Cnative -J/opt/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /Users/kirill/.julia/v0.6/ApproxFun/test/runtests.jl`, ProcessExited(1)) [1]

============================================================================================================================================================================================================
ERROR: ApproxFun had test errors
```

I don't understand what went wrong there either. Could it really be just that sensitive to roundoff? I thought it would be okay.

**Comment by MikaelSlevinsky** [comment]
Perhaps another fix to consider is for `in` to have a new method for real types:
```julia
Base.in(x::S, d::IntervalDomain{T}) where {S<:Real, T<:Real} = d.a ≤ x ≤ d.b
```

**Comment by ikirill** [comment]
@MikaelSlevinsky Does this line look right to you? https://github.com/JuliaApproximation/ApproxFun.jl/blob/f016b3ffe880110c65163a8f5cecb4acb2fa8a66/src/Fun/Domain.jl#L117

As soon as `abs(b-a)/2` is big enough, the safety factor of `100eps/sc` is insufficient and there is no longer any tolerance for roundoff errors. In the example above:
```
julia> w(domain(w).a)
sc = 25.644681553212223
-(one(T)) - (100 * eps(T)) / sc = -1.0000000000000009
ry = -1.000000000000001
0.0

julia> -1.0000000000000009 <= -1.000000000000001 # This is -1-5eps() <= -1-4eps()
false
```

**Comment by ikirill** [comment]
Also, wouldn't an error in a numerically unstable `tocanonical` affect the function values themselves at the endpoint? That wouldn't be fixed by adjusting `in`.

**Comment by MikaelSlevinsky** [comment]
I think we'd have to be precise about numerical instability.

The current `mobius` is perfectly suited for symmetric intervals of arbitrarily large sizes:
https://github.com/JuliaApproximation/ApproxFun.jl/blob/a4141f6562eec07ec85752af355e744bf1a3a5f7/src/Domains/Segment.jl#L79 In this case, the sum of the endpoints is exactly zero and multiplication by `2` shifts the bits. The division is then performed to high relative accuracy.

**Comment by ikirill** [comment]
I see, I didn't think about that case.

**Comment by dlfivefifty** [comment]
>  `@test norm.(f,[1,2]) == norm.(F,[1,2]) == [norm(f[1],1),norm(f[2],2)] # isa Vector{Float64} `

Maybe change this to 
```julia
 @test norm.(f,[1,2]) ≈ norm.(F,[1,2]) ≈ [norm(f[1],1),norm(f[2],2)] # isa Vector{Float64} 
```

**Comment by dlfivefifty** [comment]
> `Base.in(x::S, d::Segment{T}) where {S<:Real, T<:Real} = min(d.a, d.b) ≤ x ≤ max(d.a, d.b)`

👍 

There is a plan to use Domains.jl, which would treat `Interval` and `Segment` separately, as well as support `ClosedInterval`/`OpenInterval`. The benefit of intervals is that there is no need to think of them as maps of the unit interval. Unfortunately while trying to switch over I hit a Julia 0.6 type inference bug.

**Pull request merged**
